project:
  type: manuscript
  render:
    - "!notes.md"

execute:
  freeze: true
  cache: true

manuscript:
  article: index.qmd

# pdf-engine: xelatex

format:
  # html:
  #   comments:
  #     hypothesis: true
  docx: default
  # jats: default
  # elsevier-pdf:
  #   keep-tex: true
  frontiers-harvard-pdf:
    keep-tex: true

  # (other formats)
